apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: visr
  annotations:
    workflows.argoproj.io/title: visr
    workflows.argoproj.io/description: |
      Data processing for the Visible Light Spectroscopy beamline (ViSR).
spec:
  entrypoint: visr
  arguments:
    parameters:
      - name: visitdir
        valueFrom:
          configMapKeyRef:
            name: sessionspaces
            key: data_directory
      - name: inpath
        value: ""
  volumes:
    - name: session
      hostPath:
        path: "{{`{{ workflow.parameters.visitdir }}`}}"
        type: Directory
  volumeClaimTemplates:
    - metadata:
        name: tmp
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 6Gi
        storageClassName: netapp
    - metadata:
        name: tmpdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: netapp

  templates:
    - name: mount-files
      script:
        image: docker.io/library/python:3.13-bookworm
        command: [bash]
        source: |
          echo '{{ .Files.Get "notebooks/visr-maths-03.ipynb" | b64enc }}' | base64 -d > /tmp/notebook.ipynb
          echo '{{ .Files.Get "notebooks/requirements.txt" | b64enc }}' | base64 -d > /tmp/requirements.txt
        volumeMounts:
          - name: tmp
            mountPath: /tmp
    - name: convert-notebook
      script:
        image: docker.io/library/python:3.13-bookworm
        command: [bash]
        source: |
          # install dependencies
          python -m venv /tmp/venv
          /tmp/venv/bin/pip install --no-cache-dir -r /tmp/requirements.txt
          /tmp/venv/bin/python -m ipykernel install --prefix=/tmp/venv --name=venv
          # create matplotlib config dir
          mkdir -p /tmp/mpl
          export MPLCONFIGDIR=/tmp/mpl
          # run notebook
          /tmp/venv/bin/python -m papermill /tmp/notebook.ipynb /tmp/notebook-parametrized.ipynb \
            -p inpath '{{`{{workflow.parameters.inpath}}`}}'
          /tmp/venv/bin/python -m jupyter nbconvert --execute --allow-errors --to html --output notebook --output-dir /tmp /tmp/notebook-parametrized.ipynb
        volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: session
            mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
      outputs:
        artifacts:
          - name: notebook
            path: /tmp/notebook.html
            archive:
              none: {}
    - name: visr
      dag:
        tasks:
          - name: mount-files
            template: mount-files
          - name: convert-notebook
            template: convert-notebook
            dependencies: [mount-files]
