name: CI

on:
  push:
  pull_request:

jobs:
 lint_workflows:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Lint Workflows
        uses: diamondlightsource/workflows@main